### ISSUE TITLE
Importing NNG fails with a lake parsing error

### ISSUE THREAD

**Issue by joaogui1** [PatrickMassot/NNG4#2]
Hi! I'm using Lean4 nighly in a M1 Mac Pro. When opening the game files I get the following error:
```
.elan/toolchains/leanprover--lean4---nightly-2022-09-23/bin/lake print-paths Init NNG.Metadata NNG.Tactics` failed:

stderr:
Error parsing '././lakefile.lean'.  Please restart the lean server after fixing the Lake configuration file.
```

**Comment by PatrickMassot** [comment]
Can you try to run `lake build` from a terminal? Hopefully the error message will be a bit more helpful.

**Comment by joaogui1** [comment]
Right, all I had to do was rename the Game Sever directory to `game-server`
